bazel_dep(name = "rules_java", version = "8.11.0")

bazel_dep(name = "rules_cc", version = "0.2.22")

bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/helly25/bazel-compile-commands-extractor.git",
    commit = "1f9360db1834d115c48279d38a97f30d64d3fd4a",
)
