load("@rules_clojure//:rules.bzl", "clojure_binary", "clojure_library")
load("@rules_graalvm//graalvm:defs.bzl", "native_image")

clojure_library(
    name = "cljlox_lib",
    srcs = [
        "src/lox/main.clj",
    ],
    resources = [
        "src/lox/analyser.cljc",
        "src/lox/ast.cljc",
        "src/lox/core.cljc",
        "src/lox/environment.cljc",
        "src/lox/error.cljc",
        "src/lox/evaluator.cljc",
        "src/lox/macros.cljc",
        "src/lox/main.clj",
        "src/lox/memory.cljc",
        "src/lox/native.cljc",
        "src/lox/parser.cljc",
        "src/lox/printer.cljc",
        "src/lox/resolver.cljc",
        "src/lox/scanner.cljc",
        "src/lox/token.cljc",
    ],
    aot = ["lox.main"],
    resource_strip_prefix = "cljlox/src",
    deps = [
        "@deps//:org_clojure_clojure",
        "@deps//:org_clojure_core_specs_alpha",
        "@deps//:org_clojure_spec_alpha",
    ],
)

clojure_binary(
    name = "cljlox",
    main_class = "lox.main",
    deps = [
        ":cljlox_lib",
    ],
)

native_image(
    name = "cljlox_native",
    executable_name = "cljlox-native",
    main_class = "lox.main",
    deps = [
        ":cljlox_lib",
    ],
    extra_args = [
        "--no-fallback",
        "--initialize-at-build-time",
        "-Dfile.encoding=UTF-8",
        "-Dsun.stdout.encoding=UTF-8",
        "-Dsun.stderr.encoding=UTF-8",
    ],
)

java_test(
    name = "cljlox_test",
    main_class = "tool.test_harness",
    size = "large",
    use_testrunner = False,
    runtime_deps = ["//tool:test-harness-lib"],
    data = [
        ":cljlox_native",
        "//:test_data",
    ],
    args = [
        "--interpreter", "$(location :cljlox_native)",
        "--dir", "craftinginterpreters/test",
        "--suite", "jlox",
    ],
)

clojure_library(
    name = "cljlox_test_lib",
    resources = [
        "test/lox/scanner_test.cljc",
        "test/lox/parser_test.cljc",
    ],
    resource_strip_prefix = "cljlox/test",
    deps = [
        ":cljlox_lib",
        "@test_deps//:metosin_malli",
        "@test_deps//:org_clojure_test_check",
    ],
)

java_test(
    name = "unit_tests",
    main_class = "clojure.main",
    args = ["-m", "kaocha.runner"],
    use_testrunner = False,
    runtime_deps = [
        ":cljlox_test_lib",
        "@test_deps//:org_clojure_clojure",
        "@test_deps//:lambdaisland_kaocha",
    ],
)
