name: clox

on:
  push:
    branches:
      - main
    paths:
      - "clox/**"
      - "scripts/clox.sh"
  pull_request:
    branches:
      - main
    paths:
      - "clox/**"
      - "scripts/clox.sh"
  workflow_dispatch:

jobs:
  build-and-test:
    name: Test clox (official dart test harness)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build clox
        run: bazel build //clox/...

      # - name: Setup Dart
      #   uses: dart-lang/setup-dart@v1
      #   with:
      #     sdk: 2.19.6
      # - name: Install Dart dependencies
      #   run: dart pub get -C craftinginterpreters/tool/
      # - name: Run Official Test Suite
      #   run: (cd craftinginterpreters && dart tool/bin/test.dart clox --interpreter ../scripts/clox.sh)
